# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

require:
  - rubocop-factory_bot
  - rubocop-packaging

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  Exclude:
    - db/migrate/*


# Layout
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 200


# Metrics
Metrics/BlockLength:
  Exclude:
    - test/factories.rb
    - test/test_helper.rb

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200


# Rails
Rails/I18nLocaleTexts:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false


# Style
Style/ClassAndModuleChildren:
  Exclude:
    - Guardfile

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
