env:
  global:
    - CC_TEST_REPORTER_ID=aa3a037907c34fd84940496048bb086978878819801109ef3f17caf66248f5d1
language: ruby
rvm:
  - 2.5.1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
